### ISSUE TITLE
Any advantage compared to the official brotli bindings?

### ISSUE THREAD

**Issue by karyon** [python-hyper/brotlicffi#142]
brotli has official python bindings with a very similar API, which is also [published to pip](https://pypi.org/project/Brotli), see here: https://github.com/google/brotli/tree/master/python

Is there any advantage of using this brotlipy package compared to the official one?

**Comment by anthrotype** [comment]
brotlipy uses cffi to wrap the brotli library, hence it is supposed to run faster on pypy.

**Comment by sethmlarson** [comment]
We clarify this within our documentation now and are recommending using `brotlicffi` on non-CPython.
