### ISSUE TITLE
Add brotli.__version__

### ISSUE THREAD

**Issue by jason-sachs** [python-hyper/brotlicffi#164]
brotlipy 0.7.0 has no brotli.__version__; brotli-python does. It would help applications / interactive use of Python to have it.

**Comment by sethmlarson** [comment]
Could you submit a PR with this change?

**Comment by sethmlarson** [comment]
This is now available in `brotlicffi` v0.8.0

**Comment by jason-sachs** [comment]
thanks! Sorry for not being able to help more directly.

**Comment by sethmlarson** [comment]
@jason-sachs No problem! Thank you for your patience :)
