### ISSUE TITLE
Add support to release aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [python-hyper/brotlicffi#180]
Problem
---------
On aarch64, pip install brotlicffi builds the wheels from source code and then install it. It requires user to have development environment installed on his system. also, it take some time to build the wheels than downloading and extracting the wheels from pypi.

Resolution
-----------
On aarch64, pip install brotlicffi should download the wheels from pypi

@sethmlarson, please let me know your interest on releasing aarch64 wheels. I can help in this.

**Comment by sethmlarson** [comment]
There are now abi3-manylinux-aarch64 wheels available on PyPI: https://pypi.org/project/brotlicffi/#files
